name: eratani
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Testing
  mocktail: ^1.0.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
